# Generated by Django 3.0.3 on 2020-03-14 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('sys_date_edit', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Counterpart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('sys_date_edit', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('tax_number', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('sys_date_edit', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('sys_date_edit', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('sys_date_edit', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('sys_date_edit', models.DateTimeField(auto_now=True)),
                ('version_date', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflowapp.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_date_add', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_document', to='docflowapp.Document')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_document', to='docflowapp.Document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='Tasks',
            field=models.ManyToManyField(blank=True, to='docflowapp.Task'),
        ),
        migrations.AddField(
            model_name='document',
            name='classifier',
            field=models.ManyToManyField(to='docflowapp.Classifier'),
        ),
        migrations.AddField(
            model_name='document',
            name='counterpart',
            field=models.ManyToManyField(blank=True, to='docflowapp.Counterpart'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflowapp.DocumentType'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='document_type',
            field=models.ManyToManyField(to='docflowapp.DocumentType'),
        ),
    ]
