# Generated by Django 3.0.3 on 2020-04-05 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('docflowapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sys_user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflowapp.Document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='sys_user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='sys_user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentconnection',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_document', to='docflowapp.Document'),
        ),
        migrations.AddField(
            model_name='documentconnection',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_document', to='docflowapp.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='Tasks',
            field=models.ManyToManyField(blank=True, to='docflowapp.Task'),
        ),
        migrations.AddField(
            model_name='document',
            name='classifier',
            field=models.ManyToManyField(to='docflowapp.Classifier'),
        ),
        migrations.AddField(
            model_name='document',
            name='counterpart',
            field=models.ManyToManyField(blank=True, null=True, to='docflowapp.Counterpart'),
        ),
        migrations.AddField(
            model_name='document',
            name='sys_user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docflowapp.DocumentType'),
        ),
        migrations.AddField(
            model_name='counterpart',
            name='sys_user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classifier',
            name='document_type',
            field=models.ManyToManyField(to='docflowapp.DocumentType'),
        ),
        migrations.AddField(
            model_name='classifier',
            name='sys_user_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
