# Generated by Django 3.0.3 on 2020-03-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflowapp', '0004_auto_20200315_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='counterpart',
            field=models.ManyToManyField(blank=True, null=True, to='docflowapp.Counterpart'),
        ),
    ]
