# Generated by Django 3.0.3 on 2020-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docflowapp', '0005_auto_20200315_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
